server:
  port: 8088
#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  jdbc.userName: root
#  jdbc.password: root
#  jdbc.url: jdbc:mysql://localhost:3306/acct
logging:
  level:
      cn.itcast: debug
      org.spaingFormwork: debug
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/acct
#    username: root
#    password: root
#mybatis:
#  configuration:
##    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.pojo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acct
    username: root
    password: root
mybatis:
  type-aliases-package: cn.itcast.pojo
#  mapper-locations: mapper/*.xml
